# docker-compose.yml
version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432
  backend:
    build: ./backend/
    env_file: .env
    command: cp -r /app/collected_static/. /backend_static/static/ 
    volumes:
      - static:/backend_static
    depends_on:
      - db
    networks:
      - backend  

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80

  networks: 
    backend: